tasks:
- command: node server.js
- command: >
    export PORT_8844_URL=$(gp url 8844);
    envsubst < index.html.template > index.html;
    curl lama.sh | sh

ports:
- port: 8080
  onOpen: open-browser
- port: 8844
  onOpen: ignore